### ISSUE TITLE
Error "No command 'string' found" on Ubuntu 15.10

### ISSUE THREAD

**Issue by mandx** [oh-my-fish/theme-es#2]
```
No command 'string' found, did you mean:
 Command 'spring' from package 'ruby-spring' (universe)
 Command 'spring' from package 'spring' (universe)
 Command 'strings' from package 'binutils-multiarch' (main)
 Command 'strings' from package 'binutils' (main)
string: command not found
~/.config/fish/functions/fish_prompt.fish (line 1): string replace b o $argv[2] 2>/dev/null
                                                    ^
in command substitution
	called on line 95 of file ~/.config/fish/functions/fish_prompt.fish
[...]
```

**Comment by eugenesvk** [comment]
I meant a builtin `string` function (I think the doc in source is this file https://github.com/fish-shell/fish-shell/blob/2f5d750393c5903e72f806fbe04d6d9da03d9191/doc_src/string.txt)
You might need to update `Fish` (maybe update it from `HEAD` with a `--HEAD` switch in Homebrew, I don't really know what version it is built into).

**Comment by mandx** [comment]
That makes sense, I'm using Fish 2.2:
```
$ fish -v
fish, version 2.2.0
```

**Comment by eugenesvk** [comment]
Yeah, mine is `fish, version 2.2.0-542-g4b2495f`
I specifically upgraded to the newer `HEAD` version (gladly it's extremely simple in Homebrew) so that I could use this `string` function for trimming etc. without having to learn syntax of an arcane (for me) utility.
I understand it's inconvenient to most of the users, who are unlikely to have the latest version, but the alternative seemed to painful for myself, so I'm unlikely to change it, sorry.
Will add a requirement to the description, though.

**Comment by mandx** [comment]
Yes, a note in the description would be nice, so people won't start creating new issues about something that won't be fixed in the theme code.

BTW, which (stable) Fish version will contain this `string` function?

**Comment by eugenesvk** [comment]
Added already.
As mentioned above, don't know about versions. I hope whichever is coming next :) since it's already part of the code.

**Comment by brycepg** [comment]
@mandx 
the `string` version is added in `Fish 2.3.0`. You can grab the source/rpm/deb/ppa from the [main website](https://fishshell.com/)

**Comment by blaisck** [comment]
Like @brycepg said, just update the `fish` to `2.3+`
``sudo apt-add-repository ppa:fish-shell/release-2
sudo apt-get update
sudo apt-get install fish``
